### ISSUE TITLE
SWORD2.py Stuck at a particular protein chain

### ISSUE THREAD

**Issue by alexandrosangeli** [DSIMB/SWORD2#3]
Hello,

I've tried running SWORD2.py on 1JFJ.pdb (Chain A) and it got stuck at "Launch SWORD" for over 8 hours. I've tried this on two different machines (the other machine was only running for a few minutes but the estimate was around 2 minutes and "Launch SWORD" was the only output I got in those 4-5 minutes).

**Comment by gabrielctn** [comment]
Hello, 
This is because the file contains several models, it corresponds to an NMR structure. SWORD2 by default parses all models and launched Protein Peeling on all structures, which would take ages because there are so many models.
Can you try again after pulling the latest changes on the repo please ? Release v1.1.1
Thank you !

**Comment by gabrielctn** [comment]
I'll close this issue. Reopen it if necessary.
